Source/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Source/main/default/objects/Feedback__c/fields/Customer_name__c.field-meta.xml
<CustomField>
    <fullName>Customer_name__c</fullName>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Source/main/default/objects/Feedback__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Source/main/default/classes/rest-api-related/test/FeedbackRESTTest.cls
@isTest
public class FeedbackRESTTest {
    
    @isTest
    static void testSaveFeedback() {
        // Mock input data
        List<Feedback__c> feedbackList = new List<Feedback__c>{
            new Feedback__c(Customer_Name__c = 'Mr X', Customer_Email__c = 'abc@ss.com', Rating__c = 1),
            new Feedback__c(Customer_Name__c = 'RAtna Bhardwaj', Customer_Email__c = 'dd.dd@rr.com', Rating__c = 3) // Existing Contact
        };

        Test.startTest();
        // Call the REST method
        String result = FeedbackREST.saveFeedback(feedbackList);
        Test.stopTest();

        // Deserialize the response
        Map<String, Object> response = (Map<String, Object>) JSON.deserializeUntyped(result);

        // Assertions
        System.assertEquals(2, response.get('successCount'), 'Two Feedback records should be there ');
    }

    @isTest
    static void testSaveFeedback_negative_withoutEmail() {
        // Mock input data
        List<Feedback__c> feedbackList = new List<Feedback__c>{
            new Feedback__c(Customer_Name__c = 'Mr X', Rating__c = 1),
            new Feedback__c(Customer_Name__c = 'RAtna Bhardwaj', Rating__c = 3) // Existing Contact
        };

        Test.startTest();
        // Call the REST method
        String result = FeedbackREST.saveFeedback(feedbackList);
        Test.stopTest();

        // Deserialize the response
        Map<String, Object> response = (Map<String, Object>) JSON.deserializeUntyped(result);

        // Assertions
        System.assertEquals(2, response.get('errorsCount'), 'Two records should be there ');
    }
}