Source/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Source/main/default/objects/Feedback__c/fields/Customer_name__c.field-meta.xml
<CustomField>
    <fullName>Customer_name__c</fullName>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Source/main/default/objects/Feedback__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Source/main/default/classes/feedback-trigger-related/test/BadReviewAutoResponseHelperTest.cls
@isTest
public class BadReviewAutoResponseHelperTest {

    @testSetup
    static void setupTestData() {

        List<Contact> contacts = new List<Contact>{
            new Contact(FirstName = 'RAtna', LastName = 'Bhardwaj', Email = 'dd.dd@rr.com')
        };
        insert contacts;
    }

    @isTest
    static void testCreateContactAndFollowupActions() {
         
        List<Feedback__c> feedbacks = new List<Feedback__c>{
            new Feedback__c(Customer_Name__c = 'Mr X', Customer_Email__c = 'abc@ss.com', Rating__c = 1),
            new Feedback__c(Customer_Name__c = 'RAtna Bhardwaj', Customer_Email__c = 'dd.dd@rr.com', Rating__c = 3) // Existing Contact
        };

        Test.startTest();
        insert feedbacks;
        Test.stopTest();

        // Verify Contacts are created for new email addresses.
        List<Contact> contacts = [SELECT Id FROM Contact];
        System.assertEquals(2, contacts.size(), 'expecting two contacts');

        // Verify Feedback records are updated with Contact lookups.
        List<Feedback__c> feedbacks2 = [SELECT Id FROM Feedback__c];
        System.assertEquals(2, feedbacks2.size(), 'Expecting 2 feedbacks');
    }
}